fshell: shell.h fshell.c fcal.c fcat.c fcp.c fdate.c fls.c fmkdir.c fmv.c frm.c fman.c fyes.c fcd.c
	gcc fshell.c fcal.c fcat.c fcp.c fdate.c fls.c fmkdir.c fmv.c frm.c fman.c fyes.c fpwd.c fcd.c -o fshell -lreadline -lncurses

clean:
	rm -f fshell 
